"""add_class_assignments_and_filtering_fields

Revision ID: 9b92792938cd
Revises: 
Create Date: 2026-09-21 19:34:26.699858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b92792938cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.alter_column('division',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'A'::character varying"))
        batch_op.drop_constraint(batch_op.f('uq_session_course_date'), type_='unique')
        batch_op.create_unique_constraint('uq_session_course_date_div', ['course_id', 'session_date', 'division'])

    with op.batch_alter_table('faculty_assignments', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.create_index(batch_op.f('ix_faculty_assignments_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_faculty_assignments_faculty_id'), ['faculty_id'], unique=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('division',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'A'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('division',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'A'::character varying"))

    with op.batch_alter_table('faculty_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faculty_assignments_faculty_id'))
        batch_op.drop_index(batch_op.f('ix_faculty_assignments_course_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_session_course_date_div', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_session_course_date'), ['course_id', 'session_date'])
        batch_op.alter_column('division',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'A'::character varying"))

    # ### end Alembic commands ###
